export const ErrorCodes = {
    // Authentication & Authorization (AUTH_*)
    AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
    AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',

    // Order Domain (ORDER_*)
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDER_INVALID_STATE: 'ORDER_INVALID_STATE',
    ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
    ORDER_INVALID_ITEMS: 'ORDER_INVALID_ITEMS',

    // Inventory Domain (INV_*)
    INV_INSUFFICIENT: 'INV_INSUFFICIENT',
    INV_PRODUCT_NOT_FOUND: 'INV_PRODUCT_NOT_FOUND',
    INV_RESERVATION_EXPIRED: 'INV_RESERVATION_EXPIRED',
    INV_RESERVATION_NOT_FOUND: 'INV_RESERVATION_NOT_FOUND',

    // Payment Domain (PAY_*)
    PAY_GATEWAY_ERROR: 'PAY_GATEWAY_ERROR',
    PAY_INSUFFICIENT_FUNDS: 'PAY_INSUFFICIENT_FUNDS',
    PAY_DECLINED: 'PAY_DECLINED',
    PAY_ALREADY_REFUNDED: 'PAY_ALREADY_REFUNDED',
    PAY_NOT_FOUND: 'PAY_NOT_FOUND',

    // Technical Errors (SYS_*)
    SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
    SYS_KAFKA_ERROR: 'SYS_KAFKA_ERROR',
    SYS_REDIS_ERROR: 'SYS_REDIS_ERROR',
    SYS_TIMEOUT: 'SYS_TIMEOUT',
    SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',

    // Validation Errors (VAL_*)
    VAL_INVALID_INPUT: 'VAL_INVALID_INPUT',
    VAL_MISSING_FIELD: 'VAL_MISSING_FIELD',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
